# Generated by Django 5.1.6 on 2026-08-14 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQuestionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('Q1', 'Q1 — Displacement (European vs Asian hornet)'), ('Q2', 'Q2 — European hornet distribution in Germany'), ('Q3', 'Q3 — Habitat correlation'), ('Q4', 'Q4 — Protected areas (low priority per Theresa)'), ('Q5', 'Q5 — Synanthropic / urban-rural behavior'), ('Q6', 'Q6 — Climate & weather impact (low priority per Theresa)')], max_length=2, unique=True)),
                ('methodology_note', models.TextField(blank=True)),
                ('uses_locality_keyword_proxy', models.BooleanField(default=False, help_text='True for Q3/Q4/Q5 — keyword-parsing of `locality` is a proxy, not a real spatial join. Known technical debt.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GbifObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_label', models.CharField(max_length=64)),
                ('scientific_name', models.CharField(max_length=128)),
                ('gbif_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(default='DE', max_length=8)),
                ('state_province', models.CharField(blank=True, max_length=128)),
                ('bundesland_gadm', models.CharField(blank=True, max_length=128)),
                ('landkreis_gadm', models.CharField(blank=True, max_length=128)),
                ('locality', models.CharField(blank=True, max_length=255)),
                ('basis_of_record', models.CharField(blank=True, max_length=64)),
                ('has_media', models.BooleanField(default=False)),
                ('photo_verified', models.BooleanField(default=False, help_text='basisOfRecord=HUMAN_OBSERVATION and has_media=True')),
                ('raw_payload', models.JSONField(blank=True, help_text='Full GBIF record, for reprocessing.', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['species_label', 'year'], name='hornet_rese_species_4ab69f_idx'), models.Index(fields=['bundesland_gadm'], name='hornet_rese_bundesl_2054cc_idx')],
            },
        ),
    ]
