# Generated by Django 5.1.6 on 2026-08-14 13:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, unique=True)),
                ('scientific_name', models.CharField(max_length=128)),
                ('color_hex', models.CharField(default='#999999', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_type', models.CharField(choices=[('sighting', 'Sighting'), ('nest', 'Nest')], default='sighting', help_text="Derived from NABU's 'Beobachtung' field (e.g. 'am/im Nest' -> nest, everything else -> sighting). Matches the mockup's ART/TYP: Nest filter.", max_length=16)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('bundesland', models.CharField(blank=True, max_length=128)),
                ('landkreis', models.CharField(blank=True, max_length=128)),
                ('locality', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('basis_of_record', models.CharField(blank=True, max_length=64)),
                ('photo_verified', models.BooleanField(default=False, help_text="True if basisOfRecord=HUMAN_OBSERVATION and media/photo present (Theresa's recommended 'safe way' filter).")),
                ('gbif_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_import', models.CharField(blank=True, help_text='Filename of the CSV batch this row came from, for traceability.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='hornet_dashboard.species')),
            ],
            options={
                'indexes': [models.Index(fields=['species', 'year'], name='hornet_dash_species_9f6e68_idx'), models.Index(fields=['bundesland'], name='hornet_dash_bundesl_c00659_idx'), models.Index(fields=['observation_type'], name='hornet_dash_observa_23f758_idx')],
            },
        ),
    ]
